function ClocRayleigh = Cl_12(E,A,Lx,rho,alpha,beta)
%CL_12
%    CLOCRAYLEIGH = CL_12(E,A,LX,RHO,ALPHA,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Jan-2019 22:38:00

t2 = Lx.^2;
t3 = 1.0./Lx;
t4 = A.*E.*beta.*t3;
t5 = A.*alpha.*rho.*t2.*(1.0./6.0);
t6 = -t4+t5;
t7 = A.*alpha.*rho.*t2.*(1.0./3.0);
t8 = t4+t7;
ClocRayleigh = reshape([t8,t6,t6,t8],[2,2]);
