function Kloc = Kl_12(E,A,Lx)
%KL_12
%    KLOC = KL_12(E,A,LX)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Jan-2019 22:37:59

t2 = 1.0./Lx;
t3 = A.*E.*t2;
Kloc = reshape([t3,-t3,-t3,t3],[2,2]);
