function MlocConsistent = Ml_12(A,Lx,rho)
%ML_12
%    MLOCCONSISTENT = ML_12(A,LX,RHO)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Jan-2019 22:38:00

t2 = Lx.^2;
t3 = A.*rho.*t2.*(1.0./6.0);
t4 = A.*rho.*t2.*(1.0./3.0);
MlocConsistent = reshape([t4,t3,t3,t4],[2,2]);
